apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
  namespace: demo-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: api
        image: node:18-alpine
        command: ["node", "-e", "require('http').createServer((req, res) => res.end('Backend API Running & Connected to DB!')).listen(8080)"]
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "mongodb://database-service:27017/app"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: demo-namespace
spec:
  selector:
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
